#pragma once

// From glfw3.h
#define KD_MOUSE_BUTTON_1 0
#define KD_MOUSE_BUTTON_2 1
#define KD_MOUSE_BUTTON_3 2
#define KD_MOUSE_BUTTON_4 3
#define KD_MOUSE_BUTTON_5 4
#define KD_MOUSE_BUTTON_6 5
#define KD_MOUSE_BUTTON_7 6
#define KD_MOUSE_BUTTON_8 7
#define KD_MOUSE_BUTTON_LAST KD_MOUSE_BUTTON_8
#define KD_MOUSE_BUTTON_LEFT KD_MOUSE_BUTTON_1
#define KD_MOUSE_BUTTON_RIGHT KD_MOUSE_BUTTON_2
#define KD_MOUSE_BUTTON_MIDDLE KD_MOUSE_BUTTON_3
